version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=xofire
      - POSTGRES_USER=xofire
      - POSTGRES_PASSWORD=xofire
  web:
    build: .
    command: bash -c "cd /code && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 && python manage.py runcrons"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db